# Generated by Django 3.1.1 on 2020-12-03 19:18

from django.db import migrations

from django.core import serializers

def load_initial(apps, schema_editor):
    with open('fixtures\initialdata.json', 'r') as data_file:
        for obj in json.load(data_file):
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_initial),
    ]
