# Generated by Django 3.1.1 on 2020-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadness_score', models.FloatField()),
                ('joy_score', models.FloatField()),
                ('fear_score', models.FloatField()),
                ('disgust_score', models.FloatField()),
                ('anger_score', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('song_id', models.CharField(max_length=50)),
            ],
        ),
    ]
