# Generated by Django 3.1.1 on 2020-12-03 18:11

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_regression'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseRegression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickle', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
