# Generated by Django 3.1.1 on 2020-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_reverseregression'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadness', models.FloatField()),
                ('joy', models.FloatField()),
                ('fear', models.FloatField()),
                ('disgust', models.FloatField()),
                ('anger', models.FloatField()),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
